[task_local]
0 8,12,21 * * * https://raw.githubusercontent.com/puz102/wjkc-checkin-ios/main/quantumultx/checkin.js, tag=KS Auto Checkin, enabled=true
30 8 * * * https://raw.githubusercontent.com/puz102/wjkc-checkin-ios/main/quantumultx/token-check.js, tag=KS Token Check, enabled=true
